### ISSUE TITLE
Cannot send mails with powermail if cors extension is activ

### ISSUE THREAD

**Issue by goeko** [pagemachine/cors#8] opened 2016-04-03 19:31 UTC
Hello,

I use powermail for my forms, but after I've install CORS I dont get confirmation page.
If I deactivate the confirmation page in powermail the mail would send with powermail extension but my success page don't show.

If I deactivate CORS, everything are okay for powermail.

But I need both extension in my project.
Is their another configuration to setup CORS for working with powermail.

**My Setup.**

Powermail -> Only config with plugin flexform (no additional TS)
Cors -> currently without any configuration

I've test for example ...

```
config.cors {
  allowOrigin = *
}
```

and

```
page.config.cors {
  allowOrigin = *
  allowMethods = GET, POST, PUT, DELETE
  allowHeaders = (
    Cache-Control,
    Content-Type
  )
  exposeHeaders (
    X-Powered-By
  )
}
```

... but nothing change.

Powermail send a `Request Payload`, maybe their is the problem for working with `CORS`?

**Comment by mbrodala** [comment] 2016-04-04 07:47
Can you check your logs (TYPO3 backend module, typo3temp, Apache/PHP-FPM, ...)? Is the Powermail form submit based on AJAX by any chance? Do you see messages in the browser console (F12) if this is the case?

**Comment by goeko** [comment] 2016-04-04 08:11
Yes, the powermail submit is based on AJAX.
In browser console I see everytime the first XHR call.

If I uncheck the confirmation page in powermail flexform,
the mail is send but the success page don't show.
Only if I uninstall CORS I get the correct behavior for powermail confirmation and success page.

With installed CORS extension I've remove everything in typo3temp folder and clear cache in install tool. But the behavior don't change furthermore.

**Comment by mbrodala** [comment] 2016-06-29 11:38
@goeko Can you check whether this is caused by the issue #7?

**Comment by mbrodala** [comment] 2016-11-02 10:04
@goeko Are there any updates here? I tend to close this issue otherwise.

**Comment by mbrodala** [comment] 2017-11-17 09:31
Closing this, please add more details if the issue persists.

**Closed as completed by mbrodala** 2017-11-17 09:31 UTC
